### ISSUE TITLE
Org-wide: Licensing

### ISSUE THREAD

**Issue by nekowinston** [catppuccin/catppuccin#1719]
We currently have a pretty strong preference for the MIT license, `catppuccin/catppuccin` itself is MIT licensed as well.

However, if you [search on GitHub](https://github.com/search?q=org%3Acatppuccin+-license%3AMIT), we have a few repositories that aren't MIT. We cleaned most of the old ports up in #176, but some remain, newer ports should all be MIT.

The question is, how do we want to handle Ports where the MIT license isn't an option because we're forking GPL work?
This came up when @Sourcastic meant to fork something for KDE.

AFAIK we could easily license ports as MIT if they're intended to work with GPL software, but we can't just fork GPL and declare that our fork is MIT.

Would like some clarification on this issue:
- Do we still strongly prefer MIT?
- Is MIT a hard requirement and are the existing GPL ports something which you'd like to re-license as MIT (asking the authors to do so)
- Which licenses do we want to have in our org, should we actually enforce any preference?

@catppuccin/core @catppuccin/maintainers 

---

Update after the [recent staff meeting](https://github.com/catppuccin/staff/blob/main/meeting-minutes/2022-11-05.md#licensing)

- [x] Ask Maintainers of GPL ports to change the license (if possible)
  - [x] https://github.com/catppuccin/gtk (completed, since it **has** to be GPL)
  - [x] https://github.com/catppuccin/cursors
  - [x] https://github.com/catppuccin/youtube
  - [x] https://github.com/catppuccin/aliucord
- [ ] Ensure proper licensing for ports. All ports need to be checked for derivative works.

**Comment by Sourcastic** [comment]
Context: Right, yeah. So the KDE theme is made up of a bunch of different components. The color scheme is original and licensed as MIT. However, there are bits like the plasma style, window decorations that need to be added. Without them, the theme would feel incomplete, as some things will be themed and others will remain as the theme the user had previously.

Problem: Making one from scratch is quite a bit of work, atm, and it's hard to find anyone to do so. Using a preexisting one causes licensing issues, and perhaps more importantly, some inconsistency. Some themes are transparent in the wrong places, or use the wrong colors. The best option is to fork some near-perfect theme and just tweak it slightly to be catppuccin-ified.  That brings licensing issues since most of the themes are GPL. Plus, if possible, it'd be neat to include our cursor theme as well. But that's GPL as well. So yes, being able to include GPL would make life easier.

Sorry for the ramblings but
Solutions:
1- Allow GPL licenses, we include a slightly tweaked theme and publish it on the KDE Store.
2- Find someone with experience in SVGs and preferably using KDE Plasma to make something from scratch. (I'll get on this and make an announcement on the discord actually now that I think about it, maybe we'll find someone else?)
3- Don't do the previous two, forget doing a global theme and leave the user to find something that fits in the catppuccin color-scheme.

**Comment by BlueFalconHD** [comment]
What about a derivative of MIT made for colorschemes. Because we don't really host code, we could make a license made for colorschemes based on MIT.
(if MIT and GPL had a baby)

**Comment by nekowinston** [comment]
Updated the original issue with a checklist of tasks to complete.

> What about a derivative of MIT made for colorschemes. Because we don't really host code, we could make a license made for colorschemes based on MIT. (if MIT and GPL had a baby)

IANAL, but creating a new license wouldn't be wise. It would just further complicate matters, making it harder for people to use our color scheme.

**Comment by nekowinston** [comment]
@sgoudham and I reached out to https://github.com/catppuccin/aliucord/pull/4 & https://github.com/catppuccin/youtube/pull/24.

[Cursors](https://github.com/catppuccin/cursors) is another case like [gtk](https://github.com/catppuccin/gtk), where it's a derivative work of a GPL licensed repo, so that's checked as well.

**Comment by nekowinston** [comment]
I don't know how I missed this before, but it seems that YouTube will also have to stay GPL3 licensed: https://github.com/catppuccin/youtube/pull/24#issuecomment-144522429.

The last point is now just to check if anything else slipped in over the past few months that should be differently licensed.

**Comment by nekowinston** [comment]
I think userstyles were the last question mark, where I wasn't sure how much stuff was "borrowed" from other stylesheets.

Since [catppuccin/userstyles](https://github.com/catppuccin/userstyles) is now a thing, with completely reworked Less stylesheets, that part of licensing should also be sorted out.

I'll go ahead and close this issue; we can make new issues on the specific repos, should anything surface in the future.
