### ISSUE TITLE
0.2.0 Clean-up

### ISSUE THREAD

**Issue by Pocco81** [catppuccin/catppuccin#176]
Title, basically. There is some backlogged work that hasn't been checked upon recently. Not that much, just a little :wink: . This issue is simply to help us track some of the long-gone yet not forgotten things around here and to aid in sorting them out. For instance:

- [x] Descriptions in every repository: some of them don't follow the "`<allusive_emoji>` Soothing pastel theme for X" and some simply don't have a description
- [x] Topics in every repository: some repositories are missing the `catppuccin` topic (the most important one) and some others just have _that_ one, so they are missing some more topics related to the app itself.
- [ ] The big, huge, humongous elephant in the room: [the ports that need to be converted to the new formats](https://github.com/orgs/catppuccin/projects/2)
- [x] Repos with the `generated from...` tag: this tag appears at the top left corner of a repository when one generates it from a template. Although our [doc shows how to avoid this](https://github.com/catppuccin/catppuccin/blob/main/docs/contributing.md#creation) some repos with these tags have slipped in, hence they need to be deleted **carefully, preserving the local copies and the git history** so that then the repo can be re-created out of that.
- [x] The port requests! some are very old. I'll try to go over each one of them and ask how's the port looking.
- [x] Duplicated port requests
- [x] Repos with badges that use outdated colors
- [x] Assests linking to the dev branch of the main repo (this one)
- [x] The headers of some repos (e.g. Catppuccin for App) don't link to the _app_'s home page
- [x] Some repos have Releases, Packages and/or Environment enabled when in reality they are not using them
- [x] Some repos are still using the legacy `master` name for what should be the `main` branch
- [x] others... (I'll add more things to the ToDo list over time if needed) 

So, yeah...

<p align="center">
  <img src="https://user-images.githubusercontent.com/58336662/174408548-7015c67f-a9cc-4389-aef4-d2e87bda9e36.png"/>
</p>

**Comment by elkrien** [comment]
How can I help? Doing ports of themes or anything else? Just let know.

**Comment by andreasgrafen** [comment]
I think org members can assign themselves to issues? Or is this just something I can do? o:
Just thought about this feature, and figured it might be something to normalise if someone wants to work on a port.

@elkrien
I guess checking either the [Update Board](https://github.com/orgs/catppuccin/projects/2) (probably preferred to be handled first) or the [open Issues](https://github.com/catppuccin/catppuccin/issues) and just picking something that seems interesting to work on is the way to go. That's what I've been doing at least while I'm procrastinating on updating the Telegram theme.. >_>

**Comment by Pocco81** [comment]
@elkrien yes, please! with this one in particular:

> The port requests! some are very old. I'll try to go over each one of them and ask how's the port looking.

Some ports are a couple of months old and so they are not up to date. So you help by going over them and asking how's the port looking and in case its "ready" if they'd be willing to update it to the latest palettes. For example:

**Comment by nekowinston** [comment]
I think we can check those last 3 boxes now 🙂

I collected those repos with missing / non-standard descriptions:
- [ ] [alfred](https://github.com/catppuccin/alfred) - "Catppuccin Alfred theme for macos"
- [ ] [emacs](https://github.com/catppuccin/emacs) - "Catppuccin theme for emacs"
- [ ] [flori-board ](https://github.com/catppuccin/floris-board) - "A catppuccin theme for floris board"
- [ ] [foot](https://github.com/catppuccin/foot) - ":kissing_cat: Soothing pastel theme for Foot" - pretty generic
- [ ] [helix](https://github.com/catppuccin/helix) - "Soothing pastel theme for Helix!"
- [ ] [kakoune](https://github.com/catppuccin/kakoune) - "Catppuccin theme for Kakoune"
- [ ] [spt](https://github.com/catppuccin/spt) - null
- [ ] [website](https://github.com/catppuccin/website) - "Soothing pastel website"
- [ ] [wezterm](https://github.com/catppuccin/wezterm) - ":shell: Soothing pastel theme for WezTerm"  - pretty generic
- [ ] [zs-syntax-highlighting ](https://github.com/catppuccin/zsh-syntax-highlighting) - "Soothing pastel theme for zsh-syntax-highlighting"
- [ ] [zutty](https://github.com/catppuccin/zutty) - "Soothing pastel theme for Zutty"

Missing topics:
- [ ] [amfora](https://github.com/catppuccin/amfora)
- [ ] [dark-reader](https://github.com/catppuccin/dark-reader)
- [ ] [discord](https://github.com/catppuccin/discord)
- [ ] [dunst](https://github.com/catppuccin/dunst)
- [ ] [emacs](https://github.com/catppuccin/emacs)
- [ ] [floris-board](https://github.com/catppuccin/floris-board)
- [ ] [fzf](https://github.com/catppuccin/fzf)
- [ ] [github-readme-stats](https://github.com/catppuccin/github-readme-stats)
- [ ] [helix](https://github.com/catppuccin/helix)
- [ ] [kakoune](https://github.com/catppuccin/kakoune)
- [ ] [libreddit](https://github.com/catppuccin/libreddit)
- [ ] [lxqt](https://github.com/catppuccin/lxqt)
- [ ] [mailspring](https://github.com/catppuccin/mailspring)
- [ ] [micro](https://github.com/catppuccin/micro)
- [ ] [sddm](https://github.com/catppuccin/sddm)
- [ ] [spicetify](https://github.com/catppuccin/spicetify)
- [ ] [spt](https://github.com/catppuccin/spt)
- [ ] [telegram](https://github.com/catppuccin/telegram)
- [ ] [vim](https://github.com/catppuccin/vim)
- [ ] [website](https://github.com/catppuccin/website)
- [ ] [whoogle](https://github.com/catppuccin/whoogle)
- [ ] [xfce4-terminal](https://github.com/catppuccin/xfce4-terminal)
- [ ] [zsh-syntax-highlighting](https://github.com/catppuccin/zsh-syntax-highlighting)


That's all the info I could collect quite quickly with `jq` and a little bit of vimfoo for formatting.
I sadly couldn't find a way to identify repos with the `generated from...` tag via API, maybe someone has an idea how to filter them.

**Comment by nekowinston** [comment]
I needed some practice with Python again, so I decided to play around with BeautifulSoup 😄
These are the template repositories:
- [ ] [alfred](https://github.com/catppuccin/alfred)
- [ ] [zutty](https://github.com/catppuccin/zutty)
- [ ] [zsh-syntax-highlighting](https://github.com/catppuccin/zsh-syntax-highlighting)

All 3 of those were mentioned before above.

**Comment by elkrien** [comment]
I've updated Dunst theme and submitted PR. Feel free to check and merge.

**Comment by nekowinston** [comment]
In regards to
> Some repos have Releases, Packages and/or Environment enabled when in reality they are not using them

I finally got around to properly scrape for them: here's my [Gist](https://gist.github.com/nekowinston/436ea2e50f447a028177606f5012d83d).
Since the output / checklist is quite long (119 lines), I left a comment on my Gist with the current output.

I'll also link to [this repo](https://github.com/valeriangalliat/github-scripts) again, which automates what you're trying to achieve, but it would require some tweaking to work for the org of course.

**Comment by elkrien** [comment]
I've updated XFCE4-terminal theme and submitted PR. Feel free to check and merge.

**Comment by nekowinston** [comment]
Uhm... @Pocco81 I just noticed a pattern with the README changes, for Blink it was fixed manually already:
```diff
- Catppuccin for <a href="https://github.com/blinksh/blink">Blink Shell</a>
+ Catppuccin for <a href="https://github.com/blinksh/blink">Shell</a>
```

Seems those repos, where you had to run the script twice, lost their first word(s) in the title:
https://github.com/catppuccin/dark-reader
https://github.com/catppuccin/github-readme-stats
https://github.com/catppuccin/papirus-folders
https://github.com/catppuccin/sublime-text
https://github.com/catppuccin/windows-terminal

**Comment by asheeeshh** [comment]
done with #139 and https://github.com/catppuccin/hyper

**Comment by elkrien** [comment]
June is over and there is still a lot to do. For example SumatraPDF is waiting since a week to be included to Catppuccin organization. Is there anyone who can check all other issues and do the clean up?

Also I have an idea to unify screenshots. From one side I like that we allow ppl to be creative but from other one I like standardization. Maybe we should do something similar to nvim screenshot - I mean the same background with title and layout? And for example some other requirements like ascii cat with fetch for terminals?

**Comment by nekowinston** [comment]
If we go the route of unifying screenshots, might I suggest creating an official tool/script for it?
It could even use mock data for the displayed values, and also be made Unicode-safe, unlike the current `pfetch-with-kitties`.

I've played around with the idea, published a [gist](https://gist.github.com/nekowinston/f81c759bf3be78c30fa15c7f5f2a6e25).
Here's how we would use it:
```sh
curl -L https://gist.githubusercontent.com/nekowinston/f81c759bf3be78c30fa15c7f5f2a6e25/raw/a67337908b35dfc6bb0641b9b32bb8c9506f9c3c/pfetch | sh
```
In action:
![In action](https://cdn.discordapp.com/attachments/923620165218869288/993892460071755786/pfetch.gif)

**Comment by andreasgrafen** [comment]
I think as of rn @Pocco81 still is the only one that can manage everything on the ORG as a whole. So for adding new things we're reliant on him.
There are some other things I should look at (and have on my list for a while now) but I haven't gotten around to actually do it bc of IRL work and the fact that I'd need to sit down and do it.. >_>

The unification of screenshots is something we've discussed quite a while ago already.. but without any real result. So I'm glad this comes up again. I actually quite like the simplistic approach of the banner on the org: Single coloured background and simple windows on top.
Regarding the ASCII kitty for terminals: The one I've been using isn't really working well with a lot of fonts. So that should be something to keep in mind too. o:

**Comment by nekowinston** [comment]
So I updated my gist, it *should* stay consistent across environments, it sets the hostname to `catppuccin`, and sets defaults for everything else.

[Gist](https://gist.github.com/nekowinston/f81c759bf3be78c30fa15c7f5f2a6e25), Command:
`curl -L https://gist.githubusercontent.com/nekowinston/f81c759bf3be78c30fa15c7f5f2a6e25/raw/09555f418db827db87f4406e3b763f8c9a1335c1/pfetch | sh`

Thanks to @andreasgrafen for the input & testing it :)

**Comment by nekowinston** [comment]
I just added topics for all repos where they were missing previously. We also don't have any repos with empty descriptions now.

I think we can consider points 1 & 2 done.

**Comment by elkrien** [comment]
> I just added topics for all repos where they were missing previously. We also don't have any repos with empty descriptions now.
> 
> 
> 
> I think we can consider points 1 & 2 done.

Helix and website repos don't have emoji.

**Comment by nekowinston** [comment]
Thanks for double-checking it, it's corrected now. Missing Emojis must've slipped through my checks yesterday. 😅

**Comment by nekowinston** [comment]
I just went through the point
- "Some repos have Releases, Packages and/or Environment enabled when in reality they are not using them"

I have disabled those where they were not in use, with two exceptions:
- [catppuccin/palette](https://github.com/catppuccin/palette)
- [catppuccin/tailwindcss](https://github.com/catppuccin/tailwindcss)

Since those have NPM packages, that ideally should also be linked there.

---

I also added a "website" to the [VSCode](https://github.com/catppuccin/vscode) repo pointing to the VSCode Marketplace link, since people had trouble finding it there when coming from GitHub.

**Comment by nekowinston** [comment]
Another org-wide issue I've noticed and cleaned up:

Repositories were missing `LICENSE` files. I've added them myself for older v0.1.0 spec repos. The last repo missing a license file is https://github.com/catppuccin/papirus-folders, where I've opened a PR. 🙂

**Comment by nekowinston** [comment]
Regarding ports that still have to be converted:

@ap-1 worked on https://github.com/ap-1/puccinier, a rewrite of puccinier, capable of converting 0.1.3 -> 0.2.0. Of course this can't guarantee perfect updates for each port, manual touch-ups might be required, but it's a great tool that I wanted to mention here.

**Comment by nekowinston** [comment]
So I scraped all repos for the wrong badge colours, this is the list of repos where there are still mistakes:
- [ ] [chrome](https://github.com/catppuccin/chrome)
- [ ] [cursors](https://github.com/catppuccin/cursors)
- [ ] [grub](https://github.com/catppuccin/grub)
- [ ] [joplin](https://github.com/catppuccin/joplin)
- [ ] [libreddit](https://github.com/catppuccin/libreddit)
- [ ] [mailspring](https://github.com/catppuccin/mailspring)
- [ ] [papirus-folders](https://github.com/catppuccin/papirus-folders)
- [ ] [plank](https://github.com/catppuccin/plank)
- [ ] [spotify-player](https://github.com/catppuccin/spotify-player)
- [ ] [tailwindcss](https://github.com/catppuccin/tailwindcss)
- [ ] [thunderbird](https://github.com/catppuccin/thunderbird)
- [ ] [vimium](https://github.com/catppuccin/vimium)
- [ ] [website-wip](https://github.com/catppuccin/website-wip)
- [ ] [youtube](https://github.com/catppuccin/youtube)
 
I'll go through them when I have the time.

**Comment by nekowinston** [comment]
> The port requests! some are very old. I'll try to go over each one of them and ask how's the port looking.

Marking this as completed as well, since we went over all of them, and relabelled where applicable some time ago.

The last point is still finishing the rest of the ports! *We're so close now!* Any help would be appreciated.
Kanban: https://github.com/orgs/catppuccin/projects/2

**Comment by isabelincorp** [comment]
Nearly 5 months later, we are now at the last 2 [ports](https://github.com/orgs/catppuccin/projects/2) ! JetBrains is being smoothed out (integrating more languages) and telegram just requires some more love and attention, so I can easily see this being done quite soon.

**Comment by sgoudham** [comment]
https://istelegramportedyet.lol

**Comment by isabelincorp** [comment]
TELEGRAM IS ALMOST THERE, THE SCREENSHOTS ARE DONE

**Comment by nekowinston** [comment]
[Telegram is finished](https://github.com/catppuccin/telegram/issues/5). This closes out all the 0.1 -> 0.2 conversions.

Many thanks to everyone who helped, particularly with the last few ports:

- Telegram: @andreasgrafen @isabelincorp @jasoncrevier @ghostx31 @NamesCode 
- Jetbrains: @sgoudham @quentinguidee @tiepp
- LxQt: @DonutDev
- Discord: @watatomo

Special thanks to those that were quick to update their ports to 0.2.0, this took a while :sweat_smile:.
@catppuccin/maintainers

But it's finally done! :tada:

**Comment by DakshG07** [comment]
OH DAMN. WE DID IT.

**Comment by sgoudham** [comment]
It's borderline criminal that @nekowinston didn't credit himself. He carries us all on his back and still moves at 100mph. It's genuinely inspiring and a great pleasure to work with him and others in the @catppuccin/staff team.

Of course, thanks to the lovely Catppuccin community for banding together and finally getting this issue cleaned. Onwards and upwards! 🎉

**Comment by BlueFalconHD** [comment]
> It's borderline criminal that @nekowinston didn't credit himself. He carries us all on his back and still moves at 100mph. It's genuinely inspiring and a great pleasure to work with him and others in the @catppuccin/staff team.
> 
> Of course, thanks to the lovely Catppuccin community for banding together and finally getting this issue cleaned up. Onwards and upwards! 🎉

This! @nekowinston you are the main reason Catppuccin is where it is today. I can say whenever whenever I open my favorite Catppuccin themed software (ahem nvim ahem), I thank you and all of the other maintainers for their service!

🖖 Catppuccin Forever
- Blue
